### ISSUE TITLE
(potential issue) OPA final.rmd knit to HTML creates personalized URL 

### ISSUE THREAD

**Issue by laurenpeterson1** [BITSS-OPA/opa-deworming#107]
Expected Behavior: 
When you knit the final opa rmd file I would expect the url to not contain the users information. 

Current Behavior: 
Shows my user information in the url when I knit the rmd file (not sure if this is supposed to happen so I wanted to create the issue). 
![Screen Shot 2021-02-05 at 2 53 33 PM](https://user-images.githubusercontent.com/71623493/107097530-fe6f7b00-67c1-11eb-9670-cf758ab3c63a.png)

**Comment by fhoces** [comment]
this happens when we knit locally. When we deploy to the website there is no reference to individual paths
