### ISSUE TITLE
Short Length of Treatment Errs

### ISSUE THREAD

**Issue by petezh** [BITSS-OPA/opa-deworming#121]
#### Issue Description

**Component:** Shiny App

**Type:** Backend error

#### Reproduction Steps

1. Input a number between 0 and 1 to the Key Assumptions tab.
2. Press 'Update Plot.'

![image](https://user-images.githubusercontent.com/27042852/113344056-73a08d80-92e5-11eb-9b0e-374ed5b783f3.png)

#### Expected Behavior

Arguments less than 1 should be valid arguments.

#### Actual Behavior

Throws error: invalid 'times' argument.

**Comment by petezh** [comment]
Fixed. Added case to handle period length < 1 in all_analysis.R.

**Comment by fhoces** [comment]
do not edit all_analysis.R. Edit the Rmd file then run the purl command to update all_analysis.R
