### ISSUE TITLE
can't seem to load image from previous subfolder

### ISSUE THREAD

**Issue by fhoces** [BITSS-OPA/opa-deworming#93]
The following line works when calling the image in the same folder as the DD. 
https://github.com/BITSS-OPA/opa-deworming/blob/4fea57b9ad6d6862bef4bd4c2133d18587a75831/code/01_final_opa.Rmd#L360

However I would like to clean up the folder and put all the images in the `images\` folder. When I do that, and call the image with `![screenshot](../images/show_details.png?display = inline-block)` it doesn't work. 

@petezh could you take a look?

**Comment by petezh** [comment]
I changed the line to ![screenshot](images/show_details.png?display =
inline-block) and was able to display the image.
ᐧ
