### ISSUE TITLE
review links (app, DD, repo) & and create a spreadsheet to track urls

### ISSUE THREAD

**Issue by fhoces** [BITSS-OPA/opa-deworming#99]
- [x] create and share a google spreadsheet with two columns: URL and description. Use it to track the URLs that are in the OPA (app, dd, and repo). 
 - [x] Review each URL in the OPA (app, dd, and repo) and make sure it is pointing in the right direction

**Comment by petezh** [comment]
https://docs.google.com/spreadsheets/d/1HJdF8wY8aOVvNiCnUECheCqLVIIk664_FzbeNq0yHEU/edit?usp=sharing

**Comment by fhoces** [comment]
When knitting in my

**Comment by fhoces** [comment]
I'm getting the following error when knitting on my computer: 

```
Quitting from lines 75-78 (01_final_opa.Rmd) 
Error in file(file, "rt") : cannot open the connection
Calls: <Anonymous> ... withVisible -> eval -> eval -> read.csv -> read.table -> file
Execution halted
```

**Comment by petezh** [comment]
I think it has to do with how different OS handle file directories (I am usually on Windows). I pushed a new version that works on my Mac too.
